# Generated by Django 5.0.1 on 2024-01-13 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_Proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('NombreProveedor', models.CharField(max_length=300)),
                ('DireccionProveedor', models.CharField(blank=True, max_length=300, null=True)),
                ('TelefonoProveedor', models.CharField(blank=True, max_length=10, null=True)),
                ('CorreoProveedor', models.CharField(blank=True, max_length=256, null=True)),
                ('SEstado', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=1)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': False,
            },
        ),
    ]
